namespace: kube-system

helmCharts:
  - name: cilium
    includeCRDs: true
    repo: https://helm.cilium.io
    releaseName: cilium
    version: 1.12.2
    valuesInline:
      k8sServiceHost: 192.168.1.89
      k8sServicePort: 6443
      tunnel: disabled
      kubeProxyReplacement: strict
      autoDirectNodeRoutes: true
      installIptablesRules: true
      l7Proxy: false
      enableCnpStatusUpdates: false
      endpointRoutes:
        enabled: true
      bpf:
        masquerade: true
      masquerade: true
      localRedirectPolicy: true
      ipv4NativeRoutingCIDR: 10.0.0.0/8
      ipam:
        mode: cluster-pool
        operator:
          clusterPoolIPv4PodCIDRList: ['10.0.0.0/8']
          clusterPoolIPv4MaskSize: 24