virtualmachines:
  vars:
    ansible_user: kim
    ansible_password: 170306
    ansible_become_password: 170306
  hosts:
    vm01:
      ansible_host: 192.168.1.89
  children:
    master:
      hosts:
        vm01:
      vars:
        k8s_kubeadm_config: kubeadm.yaml
        k8s_create_directories: ['/opt/local-path-provisioner']