

- hosts: "{{ group | default('master') }}"
  become: true
  tasks:
    - name: Include the initial playbook
      include_tasks: setup.yaml
      vars:
        hostip: '{{ ansible_host }}'
        hostname: '{{ inventory_hostname }}'

    - name: Include the external etcd playbook
      include_tasks: setup-etcd.yaml
      when: k8s_etcd_ca_crt is defined and k8s_etcd_apiserver_crt is defined and k8s_etcd_apiserver_key is defined

    - name: Copy the kubeadm configuration file to server location
      copy: src={{ k8s_kubeadm_config }} dest=/tmp/kubeadm-config.yaml mode=0644

    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --upload-certs --config /tmp/kubeadm-config.yaml
      register: kubeadm_output
    - debug: var=kubeadm_output.stdout_lines

  handlers:
    - name: Reboot
      reboot: