- hosts: master:vm01
  become: true
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: '{{ packages }}'
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - conntrack
          - iptables
          - rsyslog

    - name: Install dependencies for K8s
      apt:
        name: '{{ packages }}'
        state: present
        update_cache: yes
      vars:
        packages:
          - socat

    - name: Add br_netfilter module
      lineinfile:
        path: /etc/modules-load.d/k8s.conf
        line: br_netfilter
        create: yes

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Enable bridge-nf-call tables
      sysctl:
        name: '{{ item }}'
        state: present
        sysctl_file: '/etc/sysctl.d/99-sysctl.conf'
        value: '1'
        reload: yes
      with_items:
        - net.ipv4.ip_forward
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-arptables
        - net.bridge.bridge-nf-call-ip6tables
