apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: node-exporter
  namespaceSelector:
    matchNames:
      - node-exporter
  endpoints:
    - path: /metrics
      port: node-exporter
      interval: 30s
      relabelings:
        - sourceLabels: [__meta_kubernetes_endpoint_node_name]
          targetLabel: node
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: kubernetes_node
