apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 30990
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
