apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana
data:
  datasources.yaml: |+
    apiVersion: 1
    datasources:
      - name: prometheus
        orgId: 1
        access: proxy
        editable: true
        type: prometheus
        url: http://prometheus-operated.prometheus.svc.cluster.local:9090
        version: 1
